#### Python Numpy Assignment
#### This notebook contains solutions to Python Numpy Assignment questions.
#### ==============================================================

Q.1) Create a 4X2 integer array and Prints its attributes

Attributes like:

a)	The shape of an array.

b)	Array dimensions.

c)	The Length of each element of the array in bytes.


In [1]:
# Import NumPy
import numpy as np

# Create a 4x2 integer array
arr = np.array([[10, 20],
                [30, 40],
                [50, 60],
                [70, 80]])

# Display the array
print("Array:\n", arr)

# a) Shape of the array
print("\nShape of the array:", arr.shape)

# b) Array dimensions
print("Array dimensions:", arr.ndim)

# c) Length of each element in bytes
print("Length of each element in bytes:", arr.itemsize)

Array:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]

Shape of the array: (4, 2)
Array dimensions: 2
Length of each element in bytes: 8


##### Conclusion:In this Question, I created a 4×2 integer NumPy array and examined its basic attributes. I learned how to determine the shape, dimensions, and memory size of each element, which helps in understanding the structure and storage of NumPy arrays.
##### ===========================================================================

Q.2)  Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [2]:
# Import NumPy
import numpy as np

# Create a 5x2 integer array from 100 to 200 with a difference of 10
arr = np.arange(100, 200, 10).reshape(5, 2)

# Display the array
print("5x2 Integer Array:\n", arr)

5x2 Integer Array:
 [[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


##### Conclusion:In this Question, I learned how to create a 5×2 integer array using np.arange() and reshape(). I also understood how to generate values within a given range while maintaining a fixed difference between consecutive elements.
##### ===========================================================================

Q.3) Add the following two NumPy arrays

import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])

arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])


In [3]:
# Import NumPy
import numpy as np

# Create the first array
arrayOne = np.array([[5, 6, 9],
                     [21, 18, 27]])

# Create the second array
arrayTwo = np.array([[15, 33, 24],
                     [4, 7, 1]])

# Add the two arrays
result = arrayOne + arrayTwo

# Display the arrays and the result
print("Array One:\n", arrayOne)
print("\nArray Two:\n", arrayTwo)
print("\nAddition of Two Arrays:\n", result)

Array One:
 [[ 5  6  9]
 [21 18 27]]

Array Two:
 [[15 33 24]
 [ 4  7  1]]

Addition of Two Arrays:
 [[20 39 33]
 [25 25 28]]


##### Conclusion:In this Question, I learned how to add two NumPy arrays using element-wise addition. This operation is useful for performing fast mathematical calculations on arrays without using loops.
##### ===========================================================================

Q.4) Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

Expected Output:
Creating 8X3 array using numpy.arange

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],[13, 14, 15]]), 
array([[16, 17, 18],[19, 20, 21]]), 
array([[22, 23, 24],[25, 26, 27]]), 
array([[28, 29, 30],[31, 32, 33]])]


In [4]:
# Import NumPy
import numpy as np

# Create an 8x3 integer array
arr = np.arange(10, 34).reshape(8, 3)

# Display the array
print("Creating 8X3 array using numpy.arange")
print(arr)

# Split the array into 4 equal-sized sub-arrays
sub_arrays = np.split(arr, 4)

# Display the sub-arrays
print("\nDividing 8X3 array into 4 sub array\n")
print(sub_arrays)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


##### Conclusion:In this Question, I learned how to create an 8×3 NumPy array using np.arange() and reshape(). I also learned how to split a large array into four equal-sized sub-arrays using the np.split() function.
##### ===========================================================================

Q.5) Write a NumPy program to generate six random integers between 10 and 30.

Expected Output:
[20 28 27 17 28 29]


In [5]:
# Import NumPy
import numpy as np

# Generate six random integers between 10 and 30
random_numbers = np.random.randint(10, 31, 6)

# Display the random numbers
print("Six Random Integers:")
print(random_numbers)

Six Random Integers:
[17 16 17 21 26 28]


##### Conclusion:In this Question, I learned how to generate random integers within a specified range using NumPy. This method is useful for creating sample data for testing, simulations, and data analysis.
##### ===========================================================================

Q.6) Write a NumPy program to generate five random numbers from the normal distribution. 

Expected Output:
[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]


In [6]:
# Import NumPy
import numpy as np

# Generate five random numbers from the normal distribution
random_numbers = np.random.randn(5)

# Display the random numbers
print("Five Random Numbers from Normal Distribution:")
print(random_numbers)

Five Random Numbers from Normal Distribution:
[0.95271995 0.43598169 0.24633214 0.84438212 1.5626515 ]


##### Conclusion:In this Question, I learned how to generate random numbers from the normal distribution using NumPy. This function is useful for simulations, statistical analysis, and machine learning applications where normally distributed data is required.
##### ===========================================================================

Q.7) Write a NumPy program to create a 3x3x3 array with random values.

In [7]:
# Import NumPy
import numpy as np

# Create a 3x3x3 array with random values
arr = np.random.random((3, 3, 3))

# Display the array
print("3x3x3 Array with Random Values:")
print(arr)

3x3x3 Array with Random Values:
[[[8.43225184e-01 1.64317207e-01 9.77499007e-01]
  [8.60543593e-04 7.90897156e-01 4.09356415e-01]
  [9.25364674e-02 2.09611654e-01 4.83178489e-01]]

 [[5.19205109e-01 4.87361748e-01 5.96718052e-01]
  [2.71781996e-01 7.43589504e-02 5.13674358e-01]
  [2.77258861e-01 1.01683973e-01 2.28236966e-01]]

 [[7.78710146e-01 9.47566214e-01 4.41272380e-01]
  [4.09828017e-01 8.07981467e-02 9.53716336e-01]
  [9.12818084e-01 5.49087078e-01 8.40930253e-01]]]


##### Conclusion:In this Question, I learned how to create a 3×3×3 NumPy array with random values using np.random.random(). This method is useful for generating sample data for testing, simulations, and machine learning applications.
##### ===========================================================================

Q.8) Write a NumPy program to normalize a 3x3 random matrix.

In [8]:
# Import NumPy
import numpy as np

# Create a 3x3 random matrix
matrix = np.random.random((3, 3))

# Normalize the matrix using Min-Max Normalization
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())

# Display the original and normalized matrices
print("Original Matrix:")
print(matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.14892877 0.10463479 0.9656901 ]
 [0.38845267 0.19269991 0.53166604]
 [0.60003001 0.60572925 0.99561868]]

Normalized Matrix:
[[0.04971356 0.         0.96640951]
 [0.31854434 0.0988403  0.47928055]
 [0.55600918 0.56240574 1.        ]]


##### Conclusion:In this Question, I learned how to create a 3×3 random matrix and normalize its values using Min-Max Normalization. Normalization scales all values between 0 and 1, making the data suitable for machine learning and data analysis tasks.
##### ===========================================================================

Q.9) Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [9]:
# Import NumPy
import numpy as np

# Create an array of numbers from 0 to 10
arr = np.arange(11)

# Shuffle the array
np.random.shuffle(arr)

# Display the shuffled array
print("Shuffled Numbers:")
print(arr)

Shuffled Numbers:
[ 4  6  2  9  0 10  7  5  3  8  1]


##### Conclusion:In this Question, I learned how to randomly shuffle the elements of a NumPy array using np.random.shuffle(). This is useful for randomizing data before performing analysis, simulations, or machine learning tasks.
##### ===========================================================================

Q.10) Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values. 

In [10]:
# Import NumPy
import numpy as np

# Create a 5x5 array with random values
arr = np.random.random((5, 5))

# Display the array
print("5x5 Random Array:")
print(arr)

# Find the minimum and maximum values
print("\nMinimum Value:", arr.min())
print("Maximum Value:", arr.max())

5x5 Random Array:
[[0.70436457 0.46801217 0.35950499 0.61454193 0.21403526]
 [0.63147854 0.54404797 0.98495384 0.45407706 0.97896108]
 [0.76392807 0.92047952 0.7245632  0.28556891 0.33501547]
 [0.07264208 0.55923378 0.42918134 0.1705769  0.52015915]
 [0.88755628 0.34479223 0.60902957 0.34605475 0.49371371]]

Minimum Value: 0.07264207710621928
Maximum Value: 0.9849538385103582


##### Conclusion:In this Question, I learned how to create a 5×5 random NumPy array and find its minimum and maximum values using the min() and max() methods. These functions are useful for analyzing the range of data in an array.
##### ===========================================================================